export * from './validateConfirPassword'
export * from './validateEmail'
export * from './validatePassword'
export * from './validateUsername'
export * from './validateService'
export * from './validatePrecio'